import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import Navber from '@/shared/Navber';
import { ToastContainer } from 'react-toastify';
import FitLogProvider from '@/context/FitLogContext';
import Footer from '@/shared/Footer';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'FitLog - Workout Library',
  description: 'Generated by FitLog',
};

export default function RootLayout({ children }: LayoutProps<'/'>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <FitLogProvider>
          <div className="sticky top-0 z-50">
            <Navber />
          </div>
          {children}
          <Footer />
          <ToastContainer />
        </FitLogProvider>
      </body>
    </html>
  );
}
